import type { Metadata } from 'next'
import { Inter, Sora } from 'next/font/google'
import './globals.css'


const sora = Sora({ subsets: ['latin'], variable: '--font-sora' })

export const metadata: Metadata = {
  title: 'Extensivo Medcof',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sora.variable}`}>{children}</body>
    </html>
  )
}
